### ISSUE TITLE
Dashboard Controller Spec is Broken

### ISSUE THREAD

**Issue by jeremyf** [samvera-deprecated/curate#111]
I believe these two lines are creating the error in the controller spec:

https://github.com/ndlib/curate/blob/renaming-partials-to-reflect-if-for-form/spec/controllers/dashboard_controller_spec.rb#L24

https://github.com/ndlib/curate/blob/renaming-partials-to-reflect-if-for-form/app/controllers/dashboard_controller.rb#L74-L80

**Comment by val99erie** [comment]
This might have to do with the fact that a Collection is automatically created for each user now (the user.person.profile, which is a Collection).  Although it looks like you were trying to exclude collections from that query, so maybe that's not the problem??

**Comment by flyingzumwalt** [comment]
Val is right.  Dashboard controller is filtering out Collections, but creating a user creates a "Profile" collection.  The test searches for everything that the user can edit, so you get that profile in the results.  

This will be automatically fixed with the work I'm doing today.
