### ISSUE TITLE
Themed Layout NoMethodError on deployment

### ISSUE THREAD

**Issue by acozine** [samvera-deprecated/curate#128]
When I generate curate_dce from curate and run the application, I see the error
`undefined method 'with_themed_layout' for DashboardController:Class (NoMethodError)`
 I can make the error go away by copying the line
`include Curate::ThemedLayoutController`
from catalog_controller.rb into dashboard_controller.rb. This happens in turn with a list of controllers including the ErrorsController, the ClassifyConcernsController, the Curate:CollectionsController, etc.

**Comment by jcoyne** [comment]
DashboardController removed.
