### ISSUE TITLE
Can't work with rails 4.0?

### ISSUE THREAD

**Issue by neversion** [samvera-deprecated/curate#211]
I add 'curate' to my Gemfile and "bundle install". I get some error:
Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    curate (>= 0) ruby depends on
      rails (= 3.2.11) ruby

```
rails (4.0.0)
```

Does it means curate can't support rails 4.0?

Thanks.

**Comment by jeremyf** [comment]
Curate is specifically for Rails 4.

Can you include your Gemfile and "gem list" output? Then we can see what might be up.

**Comment by neversion** [comment]
Appreciate for your reply.

**\* LOCAL GEMS ***

actionmailer (4.0.0)
actionpack (4.0.0)
active-fedora (6.5.1, 6.4.5)
activemodel (4.0.0)
activerecord (4.0.0)
activerecord-deprecated_finders (1.0.3)
activeresource (4.0.0)
activesupport (4.0.0)
acts_as_follower (0.2.0, 0.1.1)
addressable (2.3.5)
arel (4.0.0)
atomic (1.1.14)
backports (3.3.5)
bcrypt-ruby (3.1.2)
blacklight (4.3.0, 4.2.2)
blacklight_advanced_search (2.1.1)
blankslate (2.1.2.4)
block_helpers (0.3.3)
bootstrap-sass (2.3.2.2)
builder (3.1.4)
bundler (1.3.5)
bundler-unload (1.0.2)
cancan (1.6.10)
carrierwave (0.9.0)
childprocess (0.3.9)
climate_control (0.0.3)
cocaine (0.5.2)
coffee-rails (4.0.0)
coffee-script (2.2.0)
coffee-script-source (1.6.3)
daemons (1.1.9)
deprecation (0.0.5)
devise (3.0.0.rc)
devise-guests (0.3.2)
diff-lcs (1.2.4)
equivalent-xml (0.3.0)
erubis (2.7.0)
execjs (2.0.2)
executable-hooks (1.2.4)
fastercsv (1.5.5)
ffi (1.9.0)
font-awesome-sass-rails (3.0.2.2)
foreigner (1.5.0)
hike (1.2.3)
hooks (0.3.1)
hydra (6.0.0)
hydra-access-controls (6.3.4)
hydra-batch-edit (1.1.1, 1.0.2)
hydra-collections (1.1.0, 1.0.0)
hydra-core (6.3.4)
hydra-derivatives (0.0.7)
hydra-file_characterization (0.2.9)
hydra-head (6.3.4)
i18n (0.6.5)
jbuilder (1.5.2)
jettywrapper (1.4.2)
jquery-rails (3.0.4)
json (1.8.0)
kaminari (0.14.1)
libv8 (3.16.14.3 x86_64-linux)
logger (1.2.8)
mail (2.5.4)
mail_form (1.5.0)
mailboxer (0.11.0)
marc (0.7.1)
mediashelf-loggable (0.4.9)
mime-types (1.25)
mini_magick (3.6.0)
mini_portile (0.5.1)
minitest (4.7.5)
multi_json (1.8.2, 1.8.1)
nest (1.1.2)
noid (0.6.6)
nokogiri (1.6.0)
nom-xml (0.5.1)
om (3.0.4)
orm_adapter (0.4.0)
paperclip (3.4.2)
parslet (1.5.0)
polyglot (0.3.3)
rack (1.5.2)
rack-protection (1.5.0)
rack-test (0.6.2)
rails (4.0.0)
rails-observers (0.1.2)
rails_autolink (1.1.4)
railties (4.0.0)
rainbow (1.1.4)
rake (10.1.0)
rdf (1.0.9)
rdf-rdfxml (1.0.1)
rdf-xsd (1.0.2.1)
rdoc (3.12.2)
redis (3.0.5)
redis-namespace (1.3.1)
ref (1.0.5)
resque (1.23.1)
resque-pool (0.3.0)
rest-client (1.6.7)
rsolr (1.0.9)
rspec-core (2.14.5)
rspec-expectations (2.14.3)
rspec-mocks (2.14.3)
rspec-rails (2.14.0)
rubydora (1.6.5)
rubygems-bundler (1.3.4)
rvm (1.11.3.8)
sass (3.2.12)
sass-rails (4.0.1, 4.0.0)
sdoc (0.3.20)
sinatra (1.4.3)
solrizer (3.1.1)
sprockets (2.10.0)
sprockets-rails (2.0.0)
sqlite3 (1.3.8)
stomp (1.3.1)
subexec (0.2.3)
sufia (3.3.1, 3.1.3)
sufia-models (3.3.1, 3.1.3)
therubyracer (0.12.0)
thor (0.18.1)
thread_safe (0.1.3)
tilt (1.4.1)
treetop (1.4.15)
trollop (1.16.2)
turbolinks (1.3.0)
tzinfo (0.3.38)
uglifier (2.2.1)
vegas (0.1.11)
warden (1.2.3)
xml-simple (1.1.2)
yaml_db (0.2.3)
zipruby (0.3.6)

**Comment by jeremyf** [comment]
And your Gemfile?

**Comment by neversion** [comment]
```
source 'http://ruby.taobao.org'
gem 'rails', '4.0.0'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'therubyracer', platforms: :ruby
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
group :doc do
  gem 'sdoc', require: false
end

gem 'sufia'
gem 'kaminari', github: 'harai/kaminari', branch: 'route_prefix_prototype'  # required to handle pagination properly in dashboard. See https://github.com/amatsuda/kaminari/pull/322
gem 'jettywrapper'
gem 'font-awesome-sass-rails'
gem "devise"
gem "devise-guests", "~> 0.3"
gem "bootstrap-sass"
group :development, :test do
  gem "rspec-rails"
  gem "jettywrapper"
end
gem 'curate'
```

**Comment by jeremyf** [comment]
Is this an existing app? Or one that is new? If so, I'd recommend removing gem 'sufia'

Sufia and Curate build from the sufia-models gem;

Also, when posting comments to github if you want monospaced, wrapped the text in ```

``
MONOSPACE HERE
\``

See https://help.github.com/articles/github-flavored-markdown#syntax-highlighting

**Comment by neversion** [comment]
I just install Sufia from https://github.com/projecthydra/sufia , and need to define custom work types. 
you suggest me to use Curate whick allow for the definition of custom Work types.
https://github.com/projecthydra/sufia/issues/231#issuecomment-26531024

I try to remove gem 'sufia', but got the same error.

**Comment by jcoyne** [comment]
The released version of curate is from some time ago (probably before rails 4.0.0 support).  Instead run it from the git repository like so:

```
gem 'curate', github: 'ndlib/curate'
```

**Comment by jcoyne** [comment]
version 0.5.0 was released which does support rails 4.
