### ISSUE TITLE
Test end to end build via `rails new -m`

### ISSUE THREAD

**Issue by jeremyf** [samvera-deprecated/curate#239]
Given that we have instructions for building the script via a Rails application template, ensure that the generated application is functional.

**Comment by jeremyf** [comment]
If you want to give this a stab, making sure you have a functioning app, that would be great: @scherztc @hortongn

**Comment by scherztc** [comment]
Glen and I have ran through this once.  We are running through the updated version with the rest of our team on Wednesday, December 4th.  We will provide observations and feedback afterwards.

**Comment by scherztc** [comment]
We @hortongn installed curate as an application yesterday (rails new my_curate_application -m https://raw.github.com/ndlib/curate/master/lib/generators/curate/application_template.rb) 

Notes:

```
Prompt for use of rubyracer(linux)
    uncomment ruby racer from gem file
Does not unzip Jetty?
    cd /app directory
    rake jetty:unzip
FITS and ImageMagick?
Launching of Resque?
```

@jeremyf, let us know your thoughts on these and whether or not we should try and integrate them into the template.
