### ISSUE TITLE
file not found in curate.js and curate.cs.scss

### ISSUE THREAD

**Issue by neversion** [samvera-deprecated/curate#270]
My env is ruby 2.0.0 and rails 4.0.0
My install steps:
1.  installing By Hand ( https://github.com/ndlib/curate)
2. start jetty
3. rails s -p 3001 
4. open 0.0.0.0:3001
after that, I got 'file not found' error.  these files are all about jquey-ui, some css and js files.  After I  delete these "require" lines in curate.js and curate.cs.scss, it works.

But what's the reason?

**Comment by jeremyf** [comment]
@neversion What was the gem version of Curate that was installed.

Do you have a gist of the changes you made?

**Comment by neversion** [comment]
curate (0.5.0)

delete this line from curate.css.scss
 *= require jquery-ui-lightness

lines from curate.js
//= require jquery-ui-1.9.2/jquery.ui.widget
//= require jquery-ui-1.9.2/jquery.ui.core
//= require jquery-ui-1.9.2/jquery.ui.menu
//= require jquery-ui-1.9.2/jquery.ui.position
//= require jquery-ui-1.9.2/jquery.ui.autocomplete

//= require jquery.tokeninput
//= require handlebars

Without deleting these lines, I will get the "file not found" error.

**Comment by jeremyf** [comment]
For some reason the 0.5.1 gem did not make it to Rubygems.org when I
released it on October 28th. I've sinced pushed the changes.

I am also close to minting a 0.5.2 version to coincide with our production
deploy.
