### ISSUE TITLE
Modernizer not found in production mode.

### ISSUE THREAD

**Issue by jcoyne** [samvera-deprecated/curate#337]
We're experiencing this problem:
http://stackoverflow.com/questions/17622858/javascript-include-tag-rails-4-generating-javascripts-instead-of-assets-i

So perhaps we should compile modernizer into application.js?

**Comment by danhorst** [comment]
I'd like to keep modernizr out of application.js; by doing so we can leave the bulk of the site's JavaScript at the bottom of the page.

We aren't encountering this problem in CurateND. The only difference I can find is a [directive to explicitly precompile](https://github.com/ndlib/curate_nd/blob/master/config/environments/production.rb#L51) modernizr in:
`config/environments/production.rb`
Unfortunately I don't think that will completely solve the problem.

I was initially able reproduce the problem in the test app for Curate proper. However, after mucking around with different asset pipeline settings for 20 minutes the javascript_include_tag always seems to behave properly. I'm not sure which, or which combination of settings make it behave. 

This is why the asset pipeline and I have a tenuous relationship.

**Comment by jcoyne** [comment]
Do you have curateND deployed somewhere in production mode?  If so, can you
view the source?  What is the path to modernizer?  Is is
/javascripts/modernizer.js? If so, does that url return anything?

-Justin

**Comment by danhorst** [comment]
If you view source on http://curate.nd.edu modernizr is at:
`<script src="/assets/modernizr-5b7dc1f596452bde24a95f15e6d63ae8.js"></script>`

**Comment by jcoyne** [comment]
Yeah, that definitely fixes it then.  We should add this to the setup instructions.
