### ISSUE TITLE
"Key not found: doi" When Adding a Work

### ISSUE THREAD

**Issue by nomadicoder** [samvera-deprecated/curate#345]
Attempted to add a work in a curate app using "Starting a New Curate Based Application" in https://github.com/projecthydra/curate/blob/master/README.md.  Both specified to and not to remotely mint DOI's.

Steps as follows:
- Used command:
  
  $ rails new my_curate_application -m https://raw.github.com/ndlib/curate/master/lib/generators/curate/application_template.rb
- Answered 'y' to
  
  Would you like to include some helfpul development tools? (i.e. better_errors, binding_of_caller, quiet_assets)
- Answered 'y' or 'n' to 
  
  Would you like to allow remote minting of Digital Object Identifiers (DOI)s?

Either case fails
- Answered 'y' to 
  
  Would you like to use jettywrapper for your SOLR and Fedora?
- Started Hydra:Jetty server
- Agreed to terms of service agreement
- Completed user profile
- Clicked 'plus' button and selected "Adding an Article"

Got error page

```
KeyError at /concern/articles/new
key not found: :doi
```

 With trace dump:

```
Hydra::RemoteIdentifier::Configuration#find_remote_service  hydra-remote_identifier (0.6.1) lib/hydra/remote_identifier/configuration.rb, line 20
Hydra::RemoteIdentifier.remote_service  hydra-remote_identifier (0.6.1) lib/hydra/remote_identifier.rb, line 55
#<Class:0x007fb003f53d58>#___sers_skng__rvm_gems_ruby_______p____curate_no_doi_gems_curate_______app_views_curation_concern_base__form_doi_html_erb___2768855590727271116_70197022069520 curate (0.5.6) app/views/curation_concern/base/_form_doi.html.erb, line 1
block in ActionView::Template#render  actionpack (4.0.0) lib/action_view/template.rb, line 143
ActiveSupport::Notifications.instrument  activesupport (4.0.0) lib/active_support/notifications.rb, line 161
ActionView::Template#render  actionpack (4.0.0) lib/action_view/template.rb, line 141
```

**Comment by jeremyf** [comment]
This is most definitely a bug. One caveat is that Curate assumed you could provide a DOI if one exists.

**Comment by nomadicoder** [comment]
It seems to fail when I answer in the affirmative. The app I created on 11/21 worked fine. I installed another app with remote minting also on another system the evening of 11/22 and it failed.

**Comment by nomadicoder** [comment]
Corrected comment: It seems to fail when I answer in the affirmative. The app I created on the morning of 11/21 worked fine. I installed another app with remote minting also on another system the evening of 11/21 and it failed.

**Comment by nomadicoder** [comment]
Instead of hitting 'y', I hit return, which is what I'm used to doing with apt-get installs. Hitting return is the same as answering no to the queries. I tried making sure I hit the 'y' key and was able to create an app that allowed me to add works.  I think this isn't a bug, pre se, but a usability issue. It should probably be addressed in the prompt. Also, if the user answers 'n', there should be a clearer message when attempting to add a work without a doi provided.

**Comment by nomadicoder** [comment]
Will create a new issue
