### ISSUE TITLE
Release 0.3.1

### ISSUE THREAD

**Issue by jcoyne** [samvera-deprecated/curate#35]
Most recent released version is 0.2.0

**Comment by jeremyf** [comment]
@jcoyne For some reason my push to ruby gems for this project is hanging.

**Comment by jcoyne** [comment]
I was noticing the repo itself is pretty massive.  Is something in here just really big?  What's the size of the .gem file?

**Comment by jeremyf** [comment]
I have added the jetty file to the repo for travis.

**Comment by jcoyne** [comment]
:/

**Comment by jeremyf** [comment]
I removed the jetty files from the built .gem file; I'll be properly patching the gem later.
