### ISSUE TITLE
Creating new curate application

### ISSUE THREAD

**Issue by banurekha** [samvera-deprecated/curate#393]
I was trying to create new curate application using  
rails new my_curate -m https://raw.github.com/ndlib/curate/master/lib/generators/curate/application_template.rb
Gemfile created is frozen to wrong gems. Here is the copy of gemfile create by generator

source 'https://rubygems.org'

gem 'rails', '3.2.11'
gem 'sqlite3'
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

gem "curate", "~> 0.6.1"
gem "better_errors", :group => :development
gem "binding_of_caller", :group => :development
gem "quiet_assets", :group => :development
gem "jettywrapper", :group => [:development, :test]

**Comment by jcoyne** [comment]
That's because the version of rails that you had installed was 3.2.11.

**Comment by ghost** [comment]
Also, I just noticed that the Curate README still has a URL for the application template that points to the old location of the repository (github.com/ndlib/curate instead of github.com/projecthydra/curate).  @jeremyf

**Comment by banurekha** [comment]
Ok.. I will change url on my generator and try it again
